import { OrganizationProfile, UserProfile } from '../../types';

export const presentationOrganizations: OrganizationProfile[] = [
  {
    id: 'NG-1001',
    name: 'Network Response Hub',
    type: 'NGO',
    address: '100 Relief Blvd',
    adminContact: 'Network Director',
    adminPhone: '555-7001',
    replenishmentProvider: 'State Warehouse',
    replenishmentEmail: 'network-logistics@example.org',
    replenishmentPhone: '555-7009',
    verified: true,
    active: true,
    registeredPopulation: 1800,
    currentBroadcast: 'Preparedness check in progress for all campuses.',
  },
  {
    id: 'CH-9921',
    name: 'Grace Community Church',
    type: 'CHURCH',
    address: '4500 Main St',
    adminContact: 'Pastor John',
    adminPhone: '555-0101',
    replenishmentProvider: 'Diocese HQ',
    replenishmentEmail: 'supply@diocese.example.org',
    replenishmentPhone: '555-9000',
    verified: true,
    active: true,
    parentOrgId: 'NG-1001',
    registeredPopulation: 220,
    currentBroadcast: 'Shelter open in gym. Bring medicine and IDs.',
  },
  {
    id: 'NGO-5500',
    name: 'Regional Aid Network',
    type: 'NGO',
    address: '200 Relief Ave',
    adminContact: 'Operations Lead',
    adminPhone: '555-0202',
    replenishmentProvider: 'State Warehouse',
    replenishmentEmail: 'aid-logistics@example.org',
    replenishmentPhone: '555-0209',
    verified: true,
    active: true,
    parentOrgId: 'NG-1001',
    registeredPopulation: 640,
    currentBroadcast: 'Water distribution active 8am–5pm.',
  },
  {
    id: 'CH-44123',
    name: 'Faith Coastal Church',
    type: 'CHURCH',
    address: '77 Harbor Rd',
    adminContact: 'Campus Pastor',
    adminPhone: '555-4412',
    replenishmentProvider: 'Network Response Hub',
    replenishmentEmail: 'coastal-support@example.org',
    replenishmentPhone: '555-4419',
    verified: true,
    active: true,
    parentOrgId: 'NG-1001',
    registeredPopulation: 310,
    currentBroadcast: 'Transport teams staging at east lot.',
  },
  {
    id: 'TX-HOPE-HUB-03',
    name: 'Hope Hub Church',
    type: 'CHURCH',
    address: '903 Pine St',
    adminContact: 'Pastor Elaine',
    adminPhone: '555-3030',
    replenishmentProvider: 'County Relief',
    replenishmentEmail: 'hopehub-supply@example.org',
    replenishmentPhone: '555-3039',
    verified: true,
    active: true,
    registeredPopulation: 140,
    currentBroadcast: 'Preparedness check complete. Monitoring updates.',
  },
];

export const presentationProfiles = {
  member: {
    id: 'demo-member-1',
    fullName: 'Maya Brooks',
    email: 'demo.member@aera.local',
    createdAt: new Date().toISOString(),
    phone: '555-2102',
    address: '102 Relief Ave',
    householdMembers: 4,
    household: [
      { id: 'hh-1', name: 'Jordan Brooks', age: '39', needs: '' },
      { id: 'hh-2', name: 'Ava Brooks', age: '9', needs: 'Asthma medication' },
      { id: 'hh-3', name: 'Sam Brooks', age: '67', needs: 'Mobility support' },
    ],
    petDetails: '1 dog',
    medicalNeeds: 'Insulin refrigeration required',
    emergencyContactName: 'Noah Brooks',
    emergencyContactPhone: '555-2199',
    emergencyContactRelation: 'Spouse',
    communityId: 'CH-9921',
    role: 'GENERAL_USER',
    language: 'en',
    active: true,
    onboardComplete: true,
    transportationAccess: false,
    medicationDependency: true,
    insulinDependency: true,
    mobilityLimitation: true,
    notifications: { push: true, sms: true, email: true },
  } as UserProfile,
  networkAdmin: {
    id: 'demo-network-admin',
    fullName: 'Noah Grant',
    email: 'demo.network.admin@aera.local',
    createdAt: new Date().toISOString(),
    phone: '555-2101',
    address: '100 Relief Blvd',
    householdMembers: 1,
    household: [],
    petDetails: '',
    medicalNeeds: '',
    emergencyContactName: 'Ops Center',
    emergencyContactPhone: '555-7000',
    emergencyContactRelation: 'Work',
    communityId: 'NG-1001',
    role: 'ORG_ADMIN',
    language: 'en',
    active: true,
    onboardComplete: true,
    notifications: { push: true, sms: true, email: true },
  } as UserProfile,
  singleOrgAdmin: {
    id: 'demo-single-admin',
    fullName: 'Pastor Elaine',
    email: 'demo.single.admin@aera.local',
    createdAt: new Date().toISOString(),
    phone: '555-3030',
    address: '903 Pine St',
    householdMembers: 1,
    household: [],
    petDetails: '',
    medicalNeeds: '',
    emergencyContactName: 'Church Office',
    emergencyContactPhone: '555-3031',
    emergencyContactRelation: 'Work',
    communityId: 'TX-HOPE-HUB-03',
    role: 'INSTITUTION_ADMIN',
    language: 'en',
    active: true,
    onboardComplete: true,
    notifications: { push: true, sms: true, email: true },
  } as UserProfile,
};
